version: '3.8'

services:
  pnc_nav:
    build:
      context: ..
      dockerfile: docker/Dockerfile.humble
    image: pnc_nav2:humble
    container_name: pnc_nav_dev
    privileged: true
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../src:/ros2_ws/src:rw
      - ~/.Xauthority:/root/.Xauthority:rw
    stdin_open: true
    tty: true
    command: bash
