<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schemas/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>pnc_nav_rviz</name>
  <version>0.1.0</version>
  <description>PNC Nav2 custom RViz panel: mapping / motion control / relocalization buttons</description>
  <maintainer email="hao@todo.todo">hao</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rviz_common</depend>
  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>cartographer_ros_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
    <rviz_common plugin="${prefix}/plugin_description.xml"/>
  </export>
</package>
